### ISSUE TITLE
Hoist functions

### ISSUE THREAD

**Issue by polybuildr** [polybuildr/balloon-lang#27]
Hoist functions based on later definitions.

```
f();
fn f() {}
```

should work.

**Comment by bollu** [comment]
I'm not sure I understand: what happens with mutual recursion?

**Comment by polybuildr** [comment]
> I'm not sure I understand: what happens with mutual recursion?

Mutual recursion works. :P The idea is that both functions need to be defined before the first call. So,

```
fn foo() { bar(); }
fn bar() { foo(); }
foo();
```

works fine because the first call is made after both functions are defined. And since the body is evaluated only after both functions are in the environment, there are no problems.

**Comment by polybuildr** [comment]
Looking at a piece of Javascript today:

```js
f();
var f = 5;
// f();
function f() {
    console.log("Hello");
}
f();
```

The last line causes an error. This leads to a lack of locality of effects, which suggests that this might not be a good idea. If you wish you declare intent first, and then give the function bodies, you could easily move them to another file and import (when importing support actually arrives).

**Comment by polybuildr** [comment]
Rejecting the idea. Can be better solved by imports when the time comes. (Some rationale at https://blog.vghaisas.com/hoisting-and-locality/).
