### ISSUE TITLE
Allow compilation without needing the LLVM stuff

### ISSUE THREAD

**Issue by polybuildr** [polybuildr/balloon-lang#36]
The LLVM repl requires LLVM to be present while building - which might not be the case with possible new contributors. Conditionally compiling it based on a feature seems like a good idea.

**Comment by bollu** [comment]
And another thing: `cargo` generates build artefacts that are around 2 gigs for the LLVM stuff. I'm not entirely sure why.

**Comment by polybuildr** [comment]
Wow, that's really large. Well, good thing we have optional dependencies and conditional compilation.
