### ISSUE TITLE
Write a Pygments lexer for Balloon

### ISSUE THREAD

**Issue by polybuildr** [polybuildr/balloon-lang#40]
Balloon is pretty simple right now, and [writing a Pygments lexer does not seem too complex](http://pygments.org/docs/lexerdevelopment/).

**Comment by ghost** [comment]
i'm working on this

**Comment by polybuildr** [comment]
@anukul implemented this in https://github.com/balloon-lang/pygments-balloon/issues/1. Thanks for the contribution! :D
